from library import *
from flask import Flask, render_template, Response, request, redirect, url_for
app = Flask(__name__)

#rendering the HTML page which has the button
@app.route("/")
def index():
    return render_template('index.html');

@app.route("/results")
def results():
    return render_template('visualize.html')
    
#background process happening without any refreshing
@app.route('/background_process_test')
def background_process_test():
    print ("Hello")
    return ("nothing")

if __name__ == "__main__":
    app.run(debug=True)
#This function returns the path that is generated by A* search from the start 
# station to the goal station using the defined successor function and hueristic 
# function to evaluate each step
# start: train station to start from
# goal: train station we are trying to get to
# successor: how we pick the next stop
# heuristic: how we evaluate the possible next stops
def generate_path(start, goal, successor_f, heuristic):
  visited = set()
  history = dict()
  distance = {start: 0}
  frontier = PriorityQueue()
  frontier.add(start)
  while frontier:
      node = frontier.pop()
      if node in visited:
          continue
      if goal(node):#change this to be if the node == goal station
          return reconstruct_path(history, start, node)
      visited.add(node)
      for successor in successor_f(node):
          frontier.add(
              successor,
              priority = distance[node] + 1 + heuristic(successor) # we may have to change this as this determines which stop we take next at each step
          )
          if (successor not in distance
              or distance[node] + 1 < distance[successor]):
              distance[successor] = distance[node] + 1
              history[successor] = node
  return None


